# Generated by Django 3.2.4 on 2021-06-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofiles_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='Profies'),
        ),
    ]
