# Generated by Django 3.2.4 on 2021-06-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofiles_profile_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='profile_pics',
        ),
    ]
