# Generated by Django 3.2.4 on 2021-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofiles_profile_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='profile_pics',
            field=models.ImageField(blank=True, upload_to='Profies'),
        ),
    ]
