# Generated by Django 3.2.4 on 2021-06-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='Friends2',
            new_name='friends2',
        ),
    ]
